### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Jeromeyoung** [sh3d0ww01f/WaterDragon#1]
![image](https://user-images.githubusercontent.com/39945364/174704565-d0dc3dfb-7ed8-4560-9664-60d728c13876.png)

**Comment by 8irdy** [comment]
me too

**Comment by sh3d0ww01f** [comment]
已更新 修复

**Comment by InkNull** [comment]
![image](https://user-images.githubusercontent.com/42135405/174924778-c484b65f-f38b-4bed-9480-e61f0e6b6205.png)
修复的版本是还没有上传么
