### ISSUE TITLE
action是有数量限制吗

### ISSUE THREAD

**Issue by LostNF** [sh3d0ww01f/WaterDragon#4]
我开了5台机子后新的机子就连接不了了，删除原有的机子新建的机子还是连接失败
![image](https://user-images.githubusercontent.com/12469527/176988312-f3f5d91d-fc68-4f75-8faf-1986f464e1bf.png)
虽然提示success但是连接状态还是false

**Comment by sh3d0ww01f** [comment]
我没有研究过有没有上限 但是这么看来 应该是有上限的吧 QAQ

**Comment by LostNF** [comment]
> 我没有研究过有没有上限 但是这么看来 应该是有上限的吧 QAQ

**Comment by LostNF** [comment]
> 我没有研究过有没有上限 但是这么看来 应该是有上限的吧 QAQ

看了下好像是按时间收费的
![image](https://user-images.githubusercontent.com/12469527/177026636-c924a609-b093-4f0d-890a-715b096ccefe.png)
![image](https://user-images.githubusercontent.com/12469527/177026639-66a1b7d7-b887-48a2-ba3f-ffc71983698d.png)
